#+MACRO: name modular_device_base_3x2
#+MACRO: version 1.2
#+TITLE: documentation_setup
#+AUTHOR: Peter Polidoro
#+EMAIL: peterpolidoro@gmail.com

* Description                                                      :noexport:
  This file sets up documentation and prepares the repository for documentation
  exporting.

* Setup                                                            :noexport:
  Dependencies:
  - imagemagik #To generate images

  Kicad:
  - Plot schematic in ./schematic/ in pdf format.
  - Generate bill of materials.
  - Plot gerbers for all important layers in ./gerbers/ in gerber format, using
    Protel filename extensions.
  - Generate drill file in ./gerbers/ in gerber format.
  - Print F.SilkS and B.SilkS in ./gerbers/ in pdf format.

  Images:
  - Take photo of top of board and save it to ./images/top.png
  - Take photo of bottom of board and save it to ./images/bottom.png

* Data                                                             :noexport:
  #+TBLNAME: repository-info
  | {{{name}}}    |
  | {{{version}}} |

* Schematic

  #+BEGIN_SRC sh :exports results :results raw
  for i in ./schematic/*.pdf; do
    echo "[[file:$i][$i]]\n"
  done
  #+END_SRC
  #+BEGIN_SRC sh :exports results :results raw
  rm -rf ./schematic/images/
  mkdir ./schematic/images
  convert -density 300 -depth 8 -quality 85 ./schematic/*.pdf ./schematic/images/schematic%02d.png
  for i in ./schematic/images/*.png; do
    echo "[[file:$i]]\n"
  done
  #+END_SRC
* Gerbers

  Save gerbers zip file and send to your favorite PCB manufacturer for
  fabrication.

  #+HEADER: :var name=repository-info[0,0]
  #+HEADER: :var version=repository-info[1,0]
  #+BEGIN_SRC sh :exports results :results raw
    rm ./gerbers/*.zip
    ZIP_FILENAME=./gerbers/${name}_v${version}.zip
    zip $ZIP_FILENAME ./gerbers/*.g* ./gerbers/*.drl -q
    for i in ./gerbers/*.zip; do
      echo "[[file:$i][$i]]\n"
    done
  #+END_SRC
  #+BEGIN_SRC sh :exports results :results raw
  rm -rf ./gerbers/images/
  mkdir ./gerbers/images
  convert -density 300 -depth 8 -quality 85 -rotate "90" ./gerbers/*.pdf ./gerbers/images/gerbers%02d.png
  for i in ./gerbers/images/*.png; do
    echo "[[file:$i]]\n"
  done
  #+END_SRC
* Bill of Materials
** PCB Parts
   [[./bom/bom_pcb.csv][./bom/bom_pcb.csv]]
   #+BEGIN_SRC sh :exports results
  cat ./bom/bom_pcb.csv
   #+END_SRC

** Additional Parts
   [[./bom/bom_pcb_add.csv][./bom/bom_pcb_add.csv]]
   #+INCLUDE: "./bom/bom_pcb_add.org"
  #  #+BEGIN_SRC sh :exports results
  # cat ./bom/bom_pcb_add.csv
  #  #+END_SRC
** Vendor Parts Lists
   #+BEGIN_SRC sh :exports results :results raw
    for i in ./bom/*order*.csv; do
      echo "[[file:$i][$i]]\n"
    done
   #+END_SRC
